// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import SliceAndDice from './SliceAndDice';
import Text from './Text';

export {
	ContactForm,
	Image,
	Quote,
	SliceAndDice,
	Text,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	slice_and_dice: SliceAndDice,
	text: Text,
};
